# Change these first
owner: administrator-traditiodelivery
repo: td-health-status

sites:
  - name: td-dev-api
    url: https://dev-api.traditiodelivery.com/api/ping
  - name: td-dev-process-api
    url: https://dev-process-api.traditiodelivery.com/api/ping
  - name: td-dev-admin-api
    url: https://dev-admin-api.traditiodelivery.com/api/ping
  - name: td-api
    url: https://api.traditiodelivery.com/api/ping
  - name: td-process-api
    url: https://process-api.traditiodelivery.com/api/ping
  - name: td-admin-process-api
    url: https://admin-api.traditiodelivery.com/api/ping

status-website:
  baseUrl: /td-health-status            # required for github.io/<repo> hosting
  logoUrl: https://traditiodelivery.com/assets/img/TraditioLogo-2.svg
  name: Traditio Services Health Status
  theme: ocean
  themeUrl: https://administrator-traditiodelivery.github.io/td-health-status/assets/styles.css
